# Generated by Django 3.0.7 on 2020-06-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software_name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=100)),
                ('website_link', models.TextField(max_length=500)),
                ('seq_qu_1', models.TextField(max_length=500)),
                ('seq_ans_1', models.TextField(max_length=250)),
                ('seq_qu_2', models.TextField(max_length=500)),
                ('seq_ans_2', models.TextField(max_length=250)),
                ('notes', models.TextField(max_length=500)),
                ('date_added', models.DateTimeField(verbose_name='date added')),
                ('date_modified', models.DateTimeField(verbose_name='data last modified')),
            ],
        ),
    ]
